### ISSUE TITLE
"Type instantiation is excessively deep and possibly infinite"

### ISSUE THREAD

**Issue by lgrahl** [davidmdm/myzod#43]
With 1.7.4 and TypeScript 4.1.5 I'm getting the following error:

```
node_modules/myzod/libs/types.d.ts:395:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

395 export declare class LazyType<T extends () => AnyType> extends Type<Infer<ReturnType<T>>> {
                         ~~~~~~~~


Found 1 error.
```

**Comment by davidmdm** [comment]
Would it be possible to have more information? Does this occur with a specific use of the library or simply when importing and building the project?

Have you tried upgrading typescript?

Typescript support for recursive types has only been getting better over time, and unfortunately by the nature of this library it involves a lot of types reflecting themselves and re-reflecting upon themselves, as schemas can wrap other arbitrary schemas.
I have run into similar issues in the past with typescript but am surprised to see it as late as 4.1.5.

My recommendation would be the to upgrade to typescript 4.2.X

**Comment by davidmdm** [comment]
I confirm that it does not work with typescript 4.1.5... I consider this to be more of a typescript-side bug, or inconsistency as there are versions previous to typescript 4.1.5 that also worked.

The only path moving forward would be to update your TS version.

**Comment by lgrahl** [comment]
Fair enough. There's another dependency holding me back which is why I'm on 4.1.5. Can you somehow declare that 4.2.x is required in the package.json?

**Comment by davidmdm** [comment]
will do

**Comment by pjamroziak** [comment]
@davidmdm 
the same situation in TS 4.3.2 :( rollback to 4.2.4 fixed problem

**Comment by jakebailey** [comment]
How are you all reproducing this? I use myzod for a few projects, and testing 4.3 doesn't show this message for me when jumping to the d.ts file, and the code that uses myzod seems to typecheck.

(Perhaps you have to actually use `lazy` to see it?)

**Comment by davidmdm** [comment]
I run the tests against version 4.3.2 using Lazy internally, I have not seen a problem outside of typescript 4.1.5.
Can you confirm your typescript version and myzod version?


I just tried running myzod in a side project for benchmarking using a lazy schema, and no issues.

Can you give a code sample that reproduces the problem?

**Comment by davidmdm** [comment]
Closing due to lack of activity and unable to reproduce.

**Comment by boy51** [comment]
@davidmdm I've come across this problem and I may have a way to reproduce.

For me the problem comes up when I'm compiling my project with `tsc`. Use the library in another project and any myzod schema will be output like this in `.d.ts` files:

```ts
export declare const XYSchema: import("myzod/libs/types").ObjectType<{
    uid: import("myzod/libs/types").StringType;
    name: import("myzod/libs/types").StringType;
    defaultId: import("myzod/libs/types").NullableType<import("myzod/libs/types").OptionalType<import("myzod/libs/types").NumberType>>;
    // etc ........
}>;
```

My schema is pretty big so it goes on like this. Maybe this error happens because of the excessive importing?

Maybe this can be avoided with some `tsc` flags?

**Comment by rymndhng** [comment]
I've run into this issue and I think the problems can be solved with `tsconfig` tweaks.

It seems that setting `"strict": "true"` makes these types of errors go away. 

For the codebase I am working on, I narrowed it down to one of the `strict` sub-options: `strictFunctionTypes`. Setting it to `true` makes this error go away.
